### ISSUE TITLE
Signature Message Verification Failed

### ISSUE THREAD

**Issue by CryptoToit** [trezor/trezor-crypto#150] opened 2018-04-25 19:36 UTC
Hi, apparently this is a know issue with Trezor? But the related previous call was closed without resolution. 

What is the plan to resolve this as it a a major stumbling block in functionality. I (and others) cannot confirm ownership of our addresses (https://etherscan.io/verifysig) and so cant engage with specific project! https://www.napoleonx.ai/

What is the plan and timeline to resolve this? How can we help??

**Comment by prusnak** [comment] 2018-04-26 15:32
Duplicate of https://github.com/trezor/trezor-core/issues/122

Unless Ethereum people decide which standard for singing/verifying messages is the  correct one, we can't do anything.

If there is a consensus to implement EIP-712 we'll do that.

You should ask Ethereum people for timeline ...

**Closed by prusnak** 2018-04-26 15:32 UTC
